# -*- coding: utf-8 -*-
{
    'name': 'Manual Bank Reconciliation',
    'version': '19.0.1.0.0',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'category': 'Accounting',
    'summary': 'Traditional bank statement reconciliation method',
    'description': """Traditional bank statement reconciliation method for Odoo 19""",
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'views/account_move_line_view.xml',
"views/bank_reconciliation_action.xml",
        'views/account_journal_dashboard_view.xml',
        'views/bank_statement_wiz_view.xml',
    ],
    'assets': {},
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}